/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAO.RetirosSinCuentaDAO;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author delll
 */
public class CrearRetiro extends javax.swing.JFrame {

    private Connection conexion;
    private RetirosSinCuentaDAO retirosSinCuentaDAO;

    /**
     * Creates new form CrearRetiro
     * @param conexion
     */
     public CrearRetiro(Connection conexion) {
        this.conexion = conexion;
        this.retirosSinCuentaDAO = new RetirosSinCuentaDAO(conexion);
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtImporteRetirar = new javax.swing.JLabel();
        importeARetirar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        botonAceptar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtImporteRetirar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtImporteRetirar.setText("Importe a retirar:");

        importeARetirar.setText("jTextField1");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Retiro sin tarjeta crear folio");

        botonAceptar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botonAceptar.setText("Aceptar");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        jButton2.setText("Salir");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(txtImporteRetirar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(importeARetirar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(botonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jButton2))
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtImporteRetirar)
                    .addComponent(importeARetirar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(botonAceptar)
                .addContainerGap(122, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**   PENDIENTE.
    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
        String importe = importeARetirar.getText();
         int folio = generarNumeroFolioConsecutivo();
        String contrasenia = generarContraseniaAleatoria();
        int numeroCuenta = obtenerNumeroCuenta();

        try {
            // Insertar el retiro sin cuenta en la base de datos
            retirosSinCuentaDAO.insertarRetiroSinCuenta(numeroCuenta, folio, "Pendiente", contrasenia);
            JOptionPane.showMessageDialog(this, "Retiro sin cuenta creado exitosamente");

            // Validar el folio y la contraseña
            boolean validacion = retirosSinCuentaDAO.validarFolioYContrasenia(folio, contrasenia);
            if (validacion) {
                
            } else {
                JOptionPane.showMessageDialog(this, "Error: Folio o contraseña inválidos");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error al crear el retiro sin cuenta: " + ex.getMessage());
            ex.printStackTrace(); // Manejo del error
        }
    }//GEN-LAST:event_botonAceptarActionPerformed
  */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JTextField importeARetirar;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel txtImporteRetirar;
    // End of variables declaration//GEN-END:variables
}
